# Generated by Django 3.0.6 on 2020-08-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Electricity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("due_date", models.DateField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
                ("datetime", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("problem", models.CharField(max_length=100)),
                ("message", models.TextField(max_length=500)),
                ("datetime", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Maid",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("due_date", models.DateField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
                ("datetime", models.DateTimeField()),
            ],
        ),
    ]
