# Generated by Django 3.0.6 on 2020-06-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_electricity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricity',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5000),
        ),
    ]
