# Generated by Django 3.0.6 on 2020-06-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200621_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5000)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
