# Generated by Django 4.1.5 on 2023-01-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("problem", models.CharField(max_length=100)),
                ("message", models.TextField(max_length=500)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
