# Generated by Django 4.1.5 on 2024-03-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profile_avatars/avatar.png', upload_to='profile_avatars'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(default='profile_cover_photos/cover_photo.jpg', upload_to='profile_cover_photos'),
        ),
    ]
