# Generated by Django 4.1.5 on 2024-04-22 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_roominvitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roommembership',
            old_name='user',
            new_name='member',
        ),
        migrations.AlterUniqueTogether(
            name='roommembership',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='roommembership',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.room'),
        ),
        migrations.AlterUniqueTogether(
            name='roominvitation',
            unique_together={('room', 'email', 'status')},
        ),
        migrations.AlterUniqueTogether(
            name='roommembership',
            unique_together={('member', 'room')},
        ),
    ]
