# Generated by Django 4.1.5 on 2024-05-05 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_user_roommembership_member_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roominvitation',
            options={'ordering': ['-pk']},
        ),
    ]
