# Generated by Django 4.1.5 on 2024-05-10 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_roominvitation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roominvitation',
            options={},
        ),
    ]
