# Generated by Django 4.1.5 on 2024-05-11 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_roominvitation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommembership',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roommembership',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
