# Generated by Django 4.2 on 2024-05-26 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_roommembership_created_on_roommembership_modified_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
