# Generated by Django 4.1.5 on 2023-01-18 19:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="electricity",
            name="datetime",
        ),
        migrations.RemoveField(
            model_name="maid",
            name="datetime",
        ),
        migrations.AddField(
            model_name="electricity",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="electricity",
            name="modified_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="maid",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="maid",
            name="modified_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
