# Generated by Django 4.2 on 2024-05-26 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0002_record_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='adder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adder', to=settings.AUTH_USER_MODEL),
        ),
    ]
