# Generated by Django 4.2 on 2024-05-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_record_adder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0), ('price__lte', 100000)), name='price_non_negative_and_less_than_100000'),
        ),
    ]
