# Generated by Django 4.2 on 2024-06-02 10:04

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import functools
import records.validators


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_record_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100000'))]),
        ),
        migrations.AlterField(
            model_name='record',
            name='purchase_date',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.CheckConstraint(check=models.Q(('purchase_date__lte', datetime.date(2024, 6, 2)), ('purchase_date__gte', datetime.date(2024, 5, 27))), name='purchase_date_within_last_six_days'),
        ),
    ]
