# Generated by Django 4.2 on 2024-06-02 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_roommembership_member'),
        ('records', '0005_alter_record_price_alter_record_purchase_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='water',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='waters', to='accounts.room'),
            preserve_default=False,
        ),
    ]
