# Generated by Django 4.2 on 2024-06-02 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0006_water_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='adder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_adder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='water',
            name='adder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='water_adder', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
