# Generated by Django 4.2 on 2024-06-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_alter_record_adder_alter_water_adder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water',
            name='purchase_date',
            field=models.DateField(),
        ),
    ]
