# Generated by Django 4.2 on 2024-06-03 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_alter_water_purchase_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='record',
            name='purchase_date_within_last_six_days',
        ),
    ]
