# Generated by Django 4.2 on 2025-02-16 10:44

import datetime
from django.db import migrations, models
import functools
import records.validators


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_remove_record_purchase_date_within_last_six_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='record',
            name='purchase_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 16, 10, 44, 33, 935883, tzinfo=datetime.timezone.utc), validators=[functools.partial(records.validators.validate_past_datetime, *(), **{'days': 6})]),
            preserve_default=False,
        ),
    ]
