# Generated by Django 4.2 on 2025-02-16 20:52

import datetime
from django.db import migrations, models
import functools
import records.validators


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_remove_record_purchase_date_record_purchase_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='water',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='water',
            name='purchase_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 16, 20, 52, 32, 40846, tzinfo=datetime.timezone.utc), validators=[functools.partial(records.validators.validate_past_datetime, *(), **{'days': 6})]),
            preserve_default=False,
        ),
    ]
