# Generated by Django 4.2 on 2025-02-18 18:05

from django.db import migrations, models
from datetime import datetime
from django.utils import timezone



def backfill_due_datetime_rows(model):
    """Backfill due_datetime using due_date values for existing rows efficiently."""

    # Skip if no data exists
    if not model.objects.exists():
        return

    for row in model.objects.iterator():
        if row.due_date:
            due_datetime = datetime.combine(row.due_date, datetime.min.time())

            # Ensure timezone-aware datetime
            if timezone.is_naive(due_datetime):
                due_datetime = timezone.make_aware(due_datetime)

            row.due_datetime = due_datetime

            # Updates only the due_datetime field
            row.save(update_fields=["due_datetime"])


def backfill_due_datetime(apps, schema_editor):
    """Backfill due_datetime using due_date values."""
    
    Electricity = apps.get_model("records", "Electricity")
    Maid = apps.get_model("records", "Maid")

    backfill_due_datetime_rows(Electricity)
    backfill_due_datetime_rows(Maid)


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_remove_water_purchase_date_water_purchase_datetime'),
    ]

    operations = [
        # Add the new due_datetime field (nullable initially)
        migrations.AddField(
            model_name='electricity',
            name='due_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='maid',
            name='due_datetime',
            field=models.DateTimeField(null=True),
        ),
        # Run the backfill script
        migrations.RunPython(backfill_due_datetime),
        # Remove the old due_date field
        migrations.RemoveField(
            model_name='electricity',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='maid',
            name='due_date',
        ),
        # Make due_datetime non-nullable
        migrations.AlterField(
            model_name="electricity",
            name="due_datetime",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="maid",
            name="due_datetime",
            field=models.DateTimeField(),
        ),
    ]
