# Generated by Django 3.0.6 on 2023-01-08 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='water',
            old_name='date',
            new_name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='water',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='water',
            name='datetime',
        ),
        migrations.AddField(
            model_name='water',
            name='adder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='water',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='water',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='water',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
