# Generated by Django 3.0.6 on 2023-01-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20230115_1808'),
        ('data', '0003_auto_20230110_0017'),
    ]

    operations = [
    ]
